jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

language: python
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

cache: pip

install:
  - pip install codecov
  - pip install -r requirements.txt
  - python build_database.py 

before_script:
  - coverage report -m app.py

script:
  - echo 1
