# coding: utf-8

"""
    Swagger REST Article

    This is the swagger file that goes with our server code  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IntersiteverticalServiceInterconnections(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interconnexion_uuid': 'str'
    }

    attribute_map = {
        'interconnexion_uuid': 'interconnexion_uuid'
    }

    def __init__(self, interconnexion_uuid=None):  # noqa: E501
        """IntersiteverticalServiceInterconnections - a model defined in Swagger"""  # noqa: E501

        self._interconnexion_uuid = None
        self.discriminator = None

        if interconnexion_uuid is not None:
            self.interconnexion_uuid = interconnexion_uuid

    @property
    def interconnexion_uuid(self):
        """Gets the interconnexion_uuid of this IntersiteverticalServiceInterconnections.  # noqa: E501


        :return: The interconnexion_uuid of this IntersiteverticalServiceInterconnections.  # noqa: E501
        :rtype: str
        """
        return self._interconnexion_uuid

    @interconnexion_uuid.setter
    def interconnexion_uuid(self, interconnexion_uuid):
        """Sets the interconnexion_uuid of this IntersiteverticalServiceInterconnections.


        :param interconnexion_uuid: The interconnexion_uuid of this IntersiteverticalServiceInterconnections.  # noqa: E501
        :type: str
        """

        self._interconnexion_uuid = interconnexion_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntersiteverticalServiceInterconnections, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntersiteverticalServiceInterconnections):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
