swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /region:
    get:
      operationId: readRegionName
      tags:
        - locals
      summary: Get the local region name
      description: Read the local region name
      x-swagger-router-controller: controllers.intersite
      responses:
        200:
          description: Successful read region name
          schema:
            properties:
              name:
                type: string
                description: Name of the local region
  /intersite-vertical:
    get:
      operationId: verticalReadAllResource
      tags:
        - resources
      summary: the inter-site Resource mapping structure GET
      description: Read the list of inter-site resources
      x-swagger-router-controller: controllers.intersite
      responses:
        200:
          description: Successful read inter-site resource list operation
          schema:
            type: array
            items:
              properties:
                resource_id:
                  type: string
                  description: ID of the inter-site resource
                resource_type:
                  type: string
                  description: Inter-site resource type (L2 or L3)
                resource_name:
                  type: string
                  description: Name of the inter-site resource
                resource_params:
                  type: string
                  description: Additional params for the inter-site resource
                resource_subresources:
                  type: array
                  description: SubResourcess to federate
                  items: 
                    properties:
                      resource_id:
                        type: integer
                      subresource_region:    
                        type: string
                      subresource_uuid:    
                        type: string  
                resource_interconnections:
                  type: array
                  description: Locally created interconnections
                  items:
                    properties:
                      interconnexion_uuid:
                        type: string
    
    post:
      operationId: verticalCreateResource
      tags:
        - resources
      summary: Creates an inter-site Resource POST
      description: Create an inter-site resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: resource
          in: body
          description: data for inter-resource creation
          required: True
          schema:
            type: object
            properties:
              type:
                type: string
                description: Type of inter-site resource
              name:
                type: string
                description: Name of the inter-site resource
              subresources:
                type: array
                description: SubResourcess belonging to the user
                items:
                  type: string 
      responses:
        201:
          description: Successful create inter-site resource operation
          schema:
            properties:
              id:
                type: string
                description: Id of the person
              type:
                type: string
                description: Inter-site resource type
              name:
                type: string
                description: Name of the inter-site resource
              subresources:
                type: array
                description: SubResourcess to federate
                items: 
                  type: string  
              interconnections:
                type: array
                description: Locally created interconnections
                items: 
                  type: string
    
  /intersite-vertical/{global_id}:
    delete:
      operationId: verticalDeleteResource
      tags:
        - resources
      summary: Deletes an inter-site Resource DELETE
      description: Deletes an inter-site resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          type: string
          required: True
          description: Id of the resource to delete
      responses:
        200:
          description: Successfully deleted a resource from resource list

    get:
      operationId: verticalReadOneResource
      tags:
        - resources
      summary: Read one inter-site Resource GET
      description: Read one inter-site resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully read resource from resource list 
          schema:
            properties:
              id:
                type: string
                description: ID of inter-site resource
              type:
                type: string
                description: Type of inter-site resource
              name:
                type: string
                description: Name of the inter-site resource
              params:
                type: string
                description: Additional params for the inter-site resource
              subresources:
                type: array
                items:
                  type: string
              interconnections:
                type: array
                items:
                  type: string

    put:
      operationId: verticalUpdateResource
      tags:
        - resources
      summary: Update an already deployed resource
      description: Update an already deployed resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          description: Global ID of the resource to update
          type: string
          required: True
        - name: resource
          in: body
          schema: 
            type: object
            properties: 
              subresources:
                type: array
                items:
                  type: string 
      responses:
        200:
          description: Successfully update resource
          schema:
            properties:
              id:
                type: string
                description: ID of inter-site resource
              type:
                type: string
                description: Type of inter-site resource
              name:
                type: string
                description: Name of the inter-site resource
              params:
                type: string
                description: Additional params for the inter-site resource
              subresources:
                type: array
                items:
                  type: string
              interconnections:
                type: array
                items:
                  type: string

  /intersite-horizontal:
    post:
      operationId: horizontalCreateResource
      tags:
        - horizontal
      summary: Horizontal request to create an inter-site Resource POST
      description: Horizontal request to create an inter-site Resource 
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: resource
          in: body
          description: data for inter-site creation
          required: True
          schema:
            type: object
            properties:
              global:
                type: string
                description: First created ID of the resource
              type:
                type: string
                description: Type of inter-site resource
              name:
                type: string
                description: Name of the inter-site resource
              params:
                type: array
                items:
                  type: string
                description: Additional params for the inter-site resource
              subresources:
                type: array
                items:
                  type: string 
      responses:
        201:
          description: Successful create inter-site resource operation
          schema:
            properties:
              global_id:
                type: string
                description: ID of inter-site resource
              type:
                type: string
                description: Type of inter-site resource
              local_subresource:
                type: string
                description: UUID of the local subresource
              local_region:
                type: string
                description: Name of the local region

    get:
      operationId: horizontalVerification
      tags:
        - horizontal
      summary: Horizontal request to verify remote items
      description: Horizontal request to verify an inter-site Resource 
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: subresource_cidr
          in: query
          description: data for inter-site verification
          type: string
          required: True
        - name: resource_type
          in: query
          description: Resource type to valite the cidr
          type: string
          required: True
        - name: global_id
          in: query
          description: Resource global ID
          type: string
          required: True
        - name: verification_type
          in: query
          description: Type of verification definer
          type: string
          required: True  
      responses:
        200:
          description: Successfully done verification 
          schema:
            properties:
              result:
                type: string
              information:
                type: string

  /intersite-horizontal/{global_id}:
    delete:
      operationId: horizontalDeleteResource
      tags:
        - horizontal
      summary: Deletes an inter-site Resource DELETE
      description: Deletes an inter-site resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          type: string
          required: True
          description: Id of the resource to delete
      responses:
        200:
          description: Successfully deleted a resource from resource list

    get:
      operationId: horizontalReadParameters
      tags:
        - horizontal
      summary: Read the local cidr of an inter-site Resource 
      description: Read one inter-site resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully read remote params from resource list 
          schema:
            properties:
              params:
                type: array
                items:
                  type: string
    put:
      operationId: horizontalUpdateResource
      tags:
        - horizontal
      summary: Update an already deployed resource
      description: Update an already deployed resource
      x-swagger-router-controller: controllers.intersite
      parameters:
        - name: global_id
          in: path
          description: Global ID of the resource to update
          type: string
          required: True
        - name: resource
          in: body
          schema: 
            type: object
            properties: 
              subresources:
                type: array
                items:
                  type: string 
              params:
                type: array
                items:
                  type: string
              post_create_refresh:
                type: string 
              name:
                type: string
              type:
                type: string
      responses:
        200:
          description: Successfully update resource
          schema:
            properties:
              id:
                type: string
                description: ID of inter-site resource
              type:
                type: string
                description: Type of inter-site resource
              name:
                type: string
                description: Name of the inter-site resource
              params:
                type: string
                description: Additional params for the inter-site resource
              subresources:
                type: array
                items:
                  type: string
              interconnections:
                type: array
                items:
                  type: string