# coding: utf-8

"""
    Swagger REST Article

    This is the swagger file that goes with our server code  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.regions_api import RegionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegionsApi(unittest.TestCase):
    """RegionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.regions_api.RegionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_region_name(self):
        """Test case for read_region_name

        Get the local region name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
