# coding: utf-8

"""
    Swagger REST Article

    This is the swagger file that goes with our server code  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.intersitevertical_service_interconnections import IntersiteverticalServiceInterconnections  # noqa: E501
from swagger_client.rest import ApiException


class TestIntersiteverticalServiceInterconnections(unittest.TestCase):
    """IntersiteverticalServiceInterconnections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntersiteverticalServiceInterconnections(self):
        """Test IntersiteverticalServiceInterconnections"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.intersitevertical_service_interconnections.IntersiteverticalServiceInterconnections()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
